apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-app
  labels:
    app: flask-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo-app
  template:
    metadata:
      labels:
        app: flask-demo-app
    spec:
      containers:
      - name: flask-app
        image: 192.168.94.198/library/flask-demo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "1.0.0"
        - name: ENVIRONMENT
          value: "production"
        - name: BUILD_TIME
          value: "2024-01-01"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-demo-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30089
  selector:
    app: flask-demo-app
